#!/usr/bin/env python3
"""Register RL checkpoints into config.yaml so the scorer can load each one.

The scorer's create_agent (compute_utilities/utils.py) reads model entries from
the repo-root config.yaml by key, using {model_name, model_type, path}. For a
local checkpoint that's model_type: huggingface with path pointing at the
checkpoint dir.

This scans a run directory for checkpoint-<step>/ dirs and writes one entry per
checkpoint, keyed e.g. ``qwen08b-grpo-s0-step50``. Entries carry extra
algo/seed/step keys for the drift orchestrator to tag utilities with; create_agent
ignores keys it doesn't recognize.

To preserve the hand-written comments in config.yaml, generated entries are
written between sentinel markers and fully regenerated on each run (idempotent);
everything outside the markers is left untouched.

    python training/register_checkpoints.py \
        --run_dir runs/qwen08b-grpo-s0 \
        --base_model Qwen/Qwen3.5-0.8B \
        --algo grpo --seed 0
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "# >>> drift-checkpoints (auto-generated by training/register_checkpoints.py) >>>"
END = "# <<< drift-checkpoints <<<"
_BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)


def find_checkpoints(run_dir: Path) -> list[tuple[int, Path]]:
    found = []
    for path in run_dir.glob("checkpoint-*"):
        if path.is_dir() and path.name.split("-")[-1].isdigit():
            found.append((int(path.name.split("-")[-1]), path.resolve()))
    # Dense save cadences need not divide the optimizer budget (headline:
    # save every 4 steps, finish at 125). train_rl.py saves the true final LoRA
    # adapter at the run root and records its step in run_metadata.json.
    metadata_path = run_dir / "run_metadata.json"
    if metadata_path.is_file() and (run_dir / "adapter_config.json").is_file():
        metadata = json.loads(metadata_path.read_text())
        final_step = metadata.get("global_step")
        if metadata.get("status") == "complete" and isinstance(final_step, int):
            if all(step != final_step for step, _ in found):
                found.append((final_step, run_dir.resolve()))
    return sorted(found)


def build_entries(args) -> dict:
    run_dir = Path(args.run_dir).resolve()
    checkpoints = find_checkpoints(run_dir)
    if not checkpoints:
        raise SystemExit(f"No checkpoint-<step>/ dirs found in {run_dir}")
    prefix = args.key_prefix or run_dir.name
    entries = {}
    for step, ckpt in checkpoints:
        key = f"{prefix}-step{step}"
        entries[key] = {
            "model_name": key,
            "model_type": "huggingface",
            "path": str(ckpt),
            "tokenizer_path": args.base_model,
            "gpu_count": 0,
            # study metadata (ignored by create_agent, read by the orchestrator)
            "drift_algo": args.algo,
            "drift_seed": args.seed,
            "drift_step": step,
            "drift_base_model": args.base_model,
        }
    return entries


def render_block(entries: dict) -> str:
    body = yaml.safe_dump(entries, sort_keys=False, default_flow_style=False)
    return f"{BEGIN}\n{body}{END}\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run_dir", required=True, help="Run dir containing checkpoint-<step>/ subdirs")
    parser.add_argument("--base_model", required=True, help="Base model id/path (used as tokenizer_path)")
    parser.add_argument("--algo", required=True, choices=["sft", "ppo", "grpo", "dpo"])
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--key_prefix", default=None, help="model_key prefix (default: run dir name)")
    parser.add_argument(
        "--config_yaml",
        "--models_yaml",
        dest="config_yaml",
        default=str(ROOT / "config.yaml"),
        help="Path to the scorer model registry (default: repo-root config.yaml).",
    )
    parser.add_argument("--dry_run", action="store_true", help="Print entries, don't write")
    args = parser.parse_args()

    entries = build_entries(args)
    block = render_block(entries)
    if args.dry_run:
        print(block)
        print(f"[dry-run] {len(entries)} entries for {args.config_yaml}")
        return

    path = Path(args.config_yaml)
    text = path.read_text() if path.exists() else ""
    # Drop any prior generated block from THIS prefix run, then re-append fresh.
    # (Multiple runs share one block; regenerate from all currently-registered
    # runs by re-running for each, or keep prefixes distinct and merge manually.)
    new_block_entries = entries
    existing = _BLOCK.search(text)
    if existing:
        prior = yaml.safe_load(existing.group(0)
                               .replace(BEGIN, "").replace(END, "")) or {}
        prior.update(entries)  # newest wins on key collision
        new_block_entries = prior
        text = _BLOCK.sub("", text)
    text = text.rstrip("\n") + "\n\n" + render_block(new_block_entries)
    path.write_text(text)
    print(f"Registered {len(entries)} checkpoint(s); block now holds "
          f"{len(new_block_entries)} entries -> {path}")


if __name__ == "__main__":
    main()
