import re


def truncate_reasoning(model_output: str | None, l=300) -> str | None:
    """Function truncates text between tags <thinking>...</thinking>

    Args:
        model_output (str): text answer generated by the model
        l (int): total reasoning length after truncation (must be >= 50)

    Returns:

    """
    if not model_output:
        return model_output

    model_output = model_output.strip()

    t_start = model_output.find("<think>")
    t_end = model_output.find("</think>")

    if t_start >= 0 and t_end < 0:
        # model didn't close reasoning
        model_output += "</think>"
        t_end = len(model_output) - 8

    if t_end >= l:
        #  """Output format: <think>some text up to 300 symbols... [total 10000 symbols] </think> answer..."""

        if t_start >= 0:
            reas_len = t_end - 7  # minus "<think>"
            left_len = t_start + 7  # save info that we have "<think>"
        else:
            reas_len = t_end
            left_len = 0  # don't have "<think>"

        mid = f"... [total {reas_len} symbols]</think>"
        mid_len = len(mid)

        left_len = max(left_len, l - mid_len)  # 'l-mid' must be greater than 0

        model_output = (
            model_output[:left_len]
            + mid
            + model_output[t_end + 8 :]  # skipping "</think>"
        )

    return model_output


def extract_code(model_output: str | None) -> str:
    """Extracts code block from answer generated by the model.

    Args:
        model_output (str): text answer generated by the model
        lmstyle (LMStyle): _description_

    Returns:
        str: Code block extracted from model answer
    """

    if not model_output:
        return ""

    # remove thinking
    t = model_output.find("</think>")
    if t >= 0:
        model_output = model_output[t + 8 :].strip()

    # extract codeblock
    md_codeblock_re = r"```(\s*(python|java|c\+\+|cpp|csharp|c\#|ts|js|typescript|javascript|rust|ruby|go|php|scala|kotlin)\s*\n)?(.*?)```"
    result = re.findall(md_codeblock_re, model_output, flags=re.DOTALL | re.IGNORECASE)

    if not result:
        return ""

    code_block = result[0][2]

    # removing reduntant output
    # remove "# YOUR CODE HERE" and "// YOUR CODE HERE"
    code_block = re.sub(
        "(#+|//+) YOUR CODE HERE", "", code_block, flags=re.DOTALL | re.IGNORECASE
    )

    return code_block
