#!/usr/bin/env python3
"""Render data/training/big5_side_by_side.md: every Big5 scenario's (single, shared) user input next to the four arm outputs, for human review of the trait contrast.

Reads the committed pools/validation splits under data/training/big5.*/ (built by scripts/build_big5_datasets.py) and writes one markdown file. The file exists so reviewers can eyeball whether the four outputs actually express the intended trait poles; it is derived data — regenerate it whenever the datasets are rebuilt. A summary block up top reports per-arm output length stats (the arms are matched on input by construction; output length is only expected to be roughly similar and is worth checking here before training).
"""

import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRAIN_DIR = os.path.join(ROOT, "data", "training")
OUT_PATH = os.path.join(TRAIN_DIR, "big5_side_by_side.md")

ARMS = ["big5.openness.high", "big5.openness.low", "big5.extraversion.high", "big5.extraversion.low"]
ARM_LABELS = {a: a.replace("big5.", "").replace(".", "-") for a in ARMS}
SPLITS = ["pool", "validation"]


def load(arm, split):
    path = os.path.join(TRAIN_DIR, arm, f"{split}.jsonl")
    with open(path) as f:
        return [json.loads(line) for line in f]


def main():
    lines = ["# Big5 SFT arms, side by side", ""]
    lines.append("One block per scenario: the shared user input (byte-identical across all four arms by construction, asserted below) followed by each arm's assistant output. Generated by `scripts/build_big5_side_by_side.py` from `data/training/big5.*/`; regenerate after rebuilding the datasets.")
    lines.append("")

    all_recs = {(a, s): load(a, s) for a in ARMS for s in SPLITS}

    # Summary: per-arm output length stats over the pool.
    lines.append("## Output length (pool, characters)")
    lines.append("")
    lines.append("| arm | mean | median | p10 | p90 |")
    lines.append("|---|---|---|---|---|")
    for a in ARMS:
        lens = [len(r["messages"][1]["content"]) for r in all_recs[(a, "pool")]]
        lines.append(f"| {ARM_LABELS[a]} | {np.mean(lens):.0f} | {np.median(lens):.0f} | {np.percentile(lens, 10):.0f} | {np.percentile(lens, 90):.0f} |")
    lines.append("")

    for split in SPLITS:
        recs = {a: all_recs[(a, split)] for a in ARMS}
        ref = recs[ARMS[0]]
        lines.append(f"## {split} ({len(ref)} scenarios)")
        lines.append("")
        for i, r0 in enumerate(ref):
            row = {a: recs[a][i] for a in ARMS}
            for a in ARMS[1:]:
                assert row[a]["messages"][0]["content"] == r0["messages"][0]["content"], f"input mismatch at {r0['id']} vs {a}"
                assert row[a]["meta"]["original_index"] == r0["meta"]["original_index"]
            meta = r0["meta"]
            lines.append(f"### {split} {i + 1} — scenario {meta['original_index']} ({meta['relation']})")
            lines.append("")
            lines.append(f"**Input (all arms):** {r0['messages'][0]['content']}")
            lines.append("")
            for a in ARMS:
                out = row[a]["messages"][1]["content"]
                lines.append(f"**{ARM_LABELS[a]}** ({len(out)} chars): {out}")
                lines.append("")
    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    size_mb = os.path.getsize(OUT_PATH) / 1e6
    print(f"wrote {os.path.relpath(OUT_PATH, ROOT)} ({size_mb:.1f} MB)")


if __name__ == "__main__":
    main()
